### ISSUE TITLE
Port .w and title functions

### ISSUE THREAD

**Issue by BennetBartmann** [BennetBartmann/Faust-Bot#8]

**Comment by BennetBartmann** [comment]
Bei dem Zug gleich &uuml; =>ü usw. implementieren.

**Comment by ravotd** [comment]
ü=>ü ? was meinst du damit? - erklär mir in ruhe abends bitte

**Comment by BennetBartmann** [comment]
& uuml ; => ü Github ist zu gut und hat das und uuml semikolon direkt aufgelöst:D

**Comment by ravotd** [comment]
disambiguation page muss irgendwie gehandhabt werden
i18n fehlt bei wiki
wiki braucht nochmal einen kritischen blick, ob das total doof so ist

**Comment by BennetBartmann** [comment]
Nein #29 und #30

**Comment by ravotd** [comment]
closed because duplicate. either make new issues or reopen old ones but not both for one and the same bus/feature /issue
