### ISSUE TITLE
create nightly build workflow

### ISSUE THREAD

**Issue by ravotd** [BennetBartmann/Faust-Bot#9]

**Comment by BennetBartmann** [comment]
Important in this is also to switch from Main Branch development to one side branch per Feature

**Comment by ravotd** [comment]
done - aber safe Shutdown sollte dennoch Gedanken bekommen. Funktioniert jetzt, dass das nightly guild script den Bot unter eindeutigem Prozess Name startet und den dann auch killt... geht sicherlich tausendmal schöner und korrekter
